#!/usr/bin/env python
import argparse


def get_notes(tag, changelog):
    delimiter = "## ["
    with open(changelog, 'r') as f:
        changelog = f.read().split(delimiter)
    version = [a for a in changelog if tag + "]" in a]
    if len(version) == 0:
        raise RuntimeWarning("Warning: Not a changelog ")
    if len(version) > 1:
        print(version)
        raise RuntimeError("Error: Found two version candidates in changelog nothing will be posted")

    text = "\n".join([v for v in version[0].split('\n')][1:]).strip()
    return text


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--tag', '-t', help='tag which should be used for a doc', )
    parser.add_argument('--changelog_file', '-c', help='file CHANGELOG.md in \'keep a changlog\' format')
    args = parser.parse_args()
    print(get_notes(args.tag, args.changelog_file))

